sudo: required

language: go
go:
  - 1.11.x
  - 1.12.x
  
env:
  - GO111MODULE=on

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fuse

script:
  - go build -x -v ./...
  - go test -a -x -v ./...
  - diff <(gofmt -d .) <("")
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash .travis/test-coverage.sh; fi
